#!/bin/bash

# Переменные
SOURCE_IP=$1
DEST_IP=$2
PORT=$3
shift 3

# Массив протоколов
PROTOCOLS=("$@")

# Цикл по протоколам
for PROTOCOL in "${PROTOCOLS[@]}"; do
    iptables -t nat -A PREROUTING -p $PROTOCOL -d $SOURCE_IP --dport $PORT -j DNAT --to-destination $DEST_IP:$PORT
    iptables -t nat -A POSTROUTING -p $PROTOCOL -m $PROTOCOL --dport $PORT -j SNAT --to-source $SOURCE_IP
done

# Проверка и добавление правил в sysctl
if ! grep -q "net.core.default_qdisc = fq" /etc/sysctl.conf; then
    echo "net.core.default_qdisc = fq" >> /etc/sysctl.conf
fi

if ! grep -q "net.ipv4.tcp_congestion_control = bbr" /etc/sysctl.conf; then
    echo "net.ipv4.tcp_congestion_control = bbr" >> /etc/sysctl.conf
fi

if ! grep -q "net.ipv4.ip_forward = 1" /etc/sysctl.conf; then
    echo "net.ipv4.ip_forward = 1" >> /etc/sysctl.conf
fi

# Применение изменений
sysctl -p

echo "Правила iptables и sysctl успешно установлены"
